---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Perl::Version: 1.011
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-Catalyst
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.90019
  Catalyst::Action::REST: 1.06
  Catalyst::Action::RenderView: 0.16
  Catalyst::ActionRole::ACL: 0.06
  Catalyst::Authentication::Credential::HTTP: 1.015
  Catalyst::Authentication::Store::DBIx::Class: 0.1503
  Catalyst::Component::InstancePerContext: 0.001001
  Catalyst::Controller::ActionRole: 0.15
  Catalyst::Devel: 1.36
  Catalyst::Manual: 5.9003
  Catalyst::Model::Adaptor: 0.10
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Authentication: 0.10018
  Catalyst::Plugin::ConfigLoader: 0.30
  Catalyst::Plugin::I18N: 0
  Catalyst::Plugin::Session: 0.36
  Catalyst::Plugin::Session::State::Cookie: 0.17
  Catalyst::Plugin::Session::Store::DBIC: 0
  Catalyst::Plugin::Session::Store::File: 0.18
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0.29
  Catalyst::Plugin::Unicode::Encoding: 0
  Catalyst::View::Email: 0
  Catalyst::View::TT: 0.39
  CatalystX::Component::Traits: 0.16
  CatalystX::LeakChecker: 0
  CatalystX::Profile: 0
  CatalystX::SimpleLogin: 0
  FCGI: 0.74
  Test::WWW::Mechanize::Catalyst: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.07
